## Deploy OpenShift

image::/images/openshift-ocp.svg[OpenShift,800,align="center"]

OpenShift v3 is a layered system designed to expose underlying Docker-formatted
container image and Kubernetes concepts as accurately as possible, with a focus
on easy composition of applications by a developer. For example, install Ruby,
push code, and add MySQL.

== OpenShift

=== Step 1:

*Use the `oc` command*

These instances have been preconfigured with `docker` and the `oc` command. The
`oc` command makes deploying OpenShift for development purposes incredibly
easy. The `oc cluster up` command starts a OpenShift all-in-one cluster with a
configured registry, router, image streams, and default templates.

.switch to root
[source]
----
sudo -i
----

.make a /data dir
[source]
----
mkdir /data
----

Next use the following command to bring up the cluster on your local machine.

[IMPORTANT]
But first, export your student number to sync up with the wildcard DNS mapped
to your instance. For example below, if you are student `0` then `export
STUDENT=0`.

.DO NOT CUT AND PASTE THIS!! Ok you can, but change the number....
[source]
----
export STUDENT=0
----

.run the oc command (you can cut & paste this)
[source]
----
oc cluster up --public-hostname=workshop.${STUDENT}.rhtps.io \
--routing-suffix=apps.ose.${STUDENT}.rhtps.io \
--host-pv-dir=/data --host-data-dir=/data \
--image=registry.access.redhat.com/openshift3/ose \
--version=v3.5
----

.Details on the `oc` command
[source]
----
oc cluster up \
   --public-hostname=workshop.${STUDENT}.rhtps.io \ <1>
   --routing-suffix=apps.ose.${STUDENT}.rhtps.io \ <2>
   --host-pv-dir=/data \ <3>
   --host-data-dir=/data  <4>
   --image=registry.access.redhat.com/openshift3/ose <5>
   --version=v3.5 <6>
----

<1> This sets OpenShift's public name to the public DNS name of your instance.

<2> This sets the wildcard domain for all of the applications you provision in OpenShift.

<3> Cluster up creates a set of persistent volumes by default. It exposes a new flag that allows setting the directory on the host for these volumes.

<4> To persist data across restarts, specify a valid host directory when starting your cluster with `oc` cluster up.

<5> Pull from the Red Hat registry to run OpenShift Container Platform. 

<6> Get the latest version of OCP 3.5.

.Successful Build (example)
[source]
----
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ...
   OpenShift server started.
   The server is accessible via web console at:
       https://workshop.0.rhtps.io:8443  <1>

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
----

<1> OpenShift Web Console, Example: `https://workshop.0.rhtps.io:8443`  (open in browser) 

=== Step 2:

*There is no step 2!*

