openshift-architecture:
  name: OpenShift Architecture Overview
environment:
  name: Lab Environment Overview
install:
  name: Installing the *oc* client tool
  vars:
    DOWNLOAD_CLIENT_WINDOWS: "https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-windows.zip"
    DOWNLOAD_CLIENT_MAC: "https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-mac.zip"
    DOWNLOAD_CLIENT_LIN32: "https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-linux-32bit.tar.gz"
    DOWNLOAD_CLIENT_LIN64: "https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-linux-64bit.tar.gz"
    OC_VERSION: "oc v1.3.0\nkubernetes v1.3.0+52492b4"
  revisions:
    ocp:
      vars:
        DOWNLOAD_CLIENT_WINDOWS: <win link>
        DOWNLOAD_CLIENT_MAC: <mac link>
        DOWNLOAD_CLIENT_LIN32: <lin link>
        DOWNLOAD_CLIENT_LIN64: <lim link>
        OC_VERSION: <status>
deploy-openshift:
  name: Deploy OpenShift Container Platform
explore:
  name: Exploring the CLI and Web Console
parksmap-architecture:
  name: Architecture Overview of the ParksMap Application
docker:
  name: Deploying our First Docker Image
simple-python:
  name: Deploy a Simple Application
scaling:
  name: Scaling
kernel-capabilities:
  name: Kernel Capabilities
selinux:
  name: SELinux
atomic-scan:
  name: Atomic Scan
s2i-overview:
  name: Deploying Source Code
routes:
  name: Creating Routes
logging:
  name: Exploring OpenShift's Logging Capabilities
permissions:
  name: Role-Based Access Control
remote-ops:
  name: Remote Operations
java:
  name: Deploying Java Code
python:
  name: Deploying Python Code
python-github:
  name: Deploying Python Code
databases:
  name: Adding a Database (MongoDB)
#  requires:
#    - java
databases-py:
  name: Adding a Database (MongoDB)
configmap:
  name: Externalizing Application Configurations
  requires:
#    - java
#    - databases
application-health:
  name: Application Health
codechanges:
  name: Using Source 2 Image for Code Changes
  requires:
#    - databases
ci-cd-overview:
  name: CI/CD Overview
pipelines:
  name: Automating Deployment with CI/CD Pipeline
canaryrelease:
  name: Canary Release to Production
  requires:
    - pipelines
templates:
  name: Using Application Templates
  vars:
    MW_NAME: "wildfly"
    MW_TEXT: "WildFly"
  revisions:
    roadshow:
      vars:
        MW_NAME: "eap"
        MW_TEXT: "JBoss EAP"
clustering:
  name: Clustering Stateful Java EE Applications
  requires:
    - permissions
quotas:
  name: Limiting application resource usage
run-as-non-root:
  name: Running a container as a non Root user
gcp-bigquery:
  name: Integrating with Google Compute Service BigQuery
practical_openscap_intro:
  name: Practical OpenSCAP - Intro
practical_openscap_install:
  name: Practical OpenSCAP - Install
practical_openscap_basics:
  name: Practical OpenSCAP - Basics
practical_openscap_scanning:
  name: Practical OpenSCAP - Scanning and Reporting
practical_openscap_remediation:
  name: Practical OpenSCAP - Remediation
